### ISSUE TITLE
To-Do List for 1.18

### ISSUE THREAD

**Issue by FrankTCA** [PG85/OpenTerrainGenerator#943]
This is my to-do list for Paper 1.18, DM me on Discord if you have other stuff. Also ping me on Discord once you've done something so I can check it.

- [x] Forge compiles
- [x] Forge runs
- [x] Paper compiles
- [x] Paper runs? - Paper _does_ run!
- [x] Change height limit to work with new values #944 
- [x] Fix code PG and I commented out getting Forge and Paper to run #945 
- [x] WorldPacker currently crashes on Forge, should be an easy fix, just have to make a new 1.18 branch with new params for screen #946 
- [ ] Probably recommend redoing caves from scratch and starting with vanilla code (see if it's possible to inherit the vanilla cavegen, if not to just rip the vanilla code and use it for us) #947 
- [x] Deepslate spawns where deepslate spawns and stone spawns where stone spawns (DisableDeepslate: bool in WorldConfig?) #944 
- [ ] Figure out if we're going to use the old method of biome generation or rewrite our method to look more realistic to 1.18 (maybe with legacy option) (I believe the current consensus is simply to continue doing it the old way of doing things)
- [ ] Rewrite the default preset #948 
- [ ] 3d biome support #947 
- [ ] New resources for the new resource types added in the last update. #949 
- [ ] They're overhauling stuff again for 1.18.2 so we need to figure that out asap

**Comment by FrankTCA** [comment]
I tested it and it was crashing on Paper, but I got it to run!

**Comment by FrankTCA** [comment]
#944 and #945 complete
